name: docker-build

on:
  push:
    branches:
      - main

jobs:
  package-and-deploy:
    uses: Public-Actions/docker-build-and-publish/.gitea/workflows/build.yml@release/1.0.0
    secrets: inherit
    with:
      docker_org: abell.registry.macslabs.de/docker
      build_context: ./
      build_file: ./src/docker/Dockerfile
